name: Baseline CI Example

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  baseline-check:
    name: Check Baseline Compatibility
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v0.1.0-alpha

      - name: Run Baseline CI
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          severity: 'warn'
          target-baseline: 'all'
          file-patterns: '**/*.js,**/*.jsx,**/*.ts,**/*.tsx,**/*.css,**/*.scss'
